version: '3'
services:
  simpleweb_0:
    build: ./SimpleWeb
    ports:
      - 9999:80
  simpleweb_1:
    build: ./SimpleWeb
    ports:
      - 56235:80
  simplewebtls_0:
    build: ./SimpleWebTls
    ports:
      - 4576:443
  simplewebtlsi_1:
    build: ./SimpleWebTls
    ports:
      - 57236:443
  simpleloginpage_0:
    build: ./WebLoginForm
    ports:
      - 1597:443

